architecture: "replicaset"
replicaCount: 5
persistence:
  size: 1Gi
auth:
  database: items-database
  existingSecret: config-secret
  username: username
service:
  nameOverride: db
nodeSelector:
  tier: mongodb
arbiter:
  enabled: false
